### ISSUE TITLE
Serious compile time regression (1-2 min to 1 hour)

### ISSUE THREAD

**Issue by korken89** [adamgreig/stm32-rs#44] opened 2018-09-10 20:28 UTC
CC https://github.com/rust-embedded/cortex-m-rt/issues/117

**Comment by adamgreig** [comment] 2018-09-10 20:43
Closing as this is presumably caused by https://github.com/rust-lang/rust/issues/54083; everything works OK on previous nightlies even with same library versions.

**Closed by adamgreig** 2018-09-10 20:43 UTC
